blank_issues_enabled: false
contact_links:
  - name: NetNewsWire app issue
    url: https://github.com/Ranchero-Software/NetNewsWire/issues/new/choose
    about: Report problems that also appear with NetNewsWire's built-in themes.
